package org.ao.collman.services;

import java.util.Optional;

import org.ao.collman.model.dao.CollaboratorRepo;
import org.ao.collman.model.dto.Collaborator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.ui.Model;

@Service
public class CollaboratorServicesImpl implements CollaboratorServiceInterface {

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private CollaboratorRepo userRepository;
	
	public String addNewUser(String name, String email, Model model) { 
		Collaborator n = new Collaborator();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}
	
	public Iterable<Collaborator> getAllUsers() {
		return userRepository.findAll();
		
	}

	public Optional<Collaborator> findById(Integer id) {
		return userRepository.findById(id);
	}

	public void deleteById(Integer id) {
		userRepository.deleteById(id);
	}

	public Collaborator save(Collaborator user) {
		return userRepository.save(user);
	}

}
