package org.ao.collman.services;

import java.util.Optional;

import org.ao.collman.model.User;
import org.ao.collman.model.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.ui.Model;

@Service
public class UserServicesImpl implements UserServicesInterface {

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	public String addNewUser(String name, String email, Model model) { 
		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}
	
	public Iterable<User> getAllUsers() {
		return userRepository.findAll();
		
	}

	public Optional<User> findById(Integer id) {
		return userRepository.findById(id);
	}

	public void deleteById(Integer id) {
		userRepository.deleteById(id);
	}

	public User save(User user) {
		return userRepository.save(user);
	}

}
